service: serverless-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  health:
    handler: handler.health
    events:
      - http:
          path: /health
          method: get
          
plugins:
  - serverless-plugin-typescript